name: build and deploy azure function

on:
  pull_request:
    branches:
      - Development
    paths:
      - py-azure-functions/**
      - ./.github/workflows/**
      
# env variables for current workflow file
env:
  AZURE_FUNCTIONAPP_NAME: 'quickpaste-dev-ca-east-func'
  
jobs:
  build-stage:
    name: build stage
    runs-on: ubuntu-latest
    
    steps:
      # checkout code to runner
      - name: checkout python code
        uses: actions/checkout@v4.1.1

      # install python on target runner os
      - name: setup python
        uses: actions/setup-python@v4.7.1
        with:
         python-version: 3.11

      # install python dependencies
      - name: install-dependencies
        run: | 
          pip install -r py-azure-functions/requirements.txt
          pip install flake8
          pip install isort
          
      # check lint
      - name: run linters against codebase
        run: | 
          flake8 ./py-azure-functions/function_app.py
          isort --check-only ./py-azure-functions/function_app.py

  deploy-stage:
    name: deploy stage
    needs: build-stage
    runs-on: ubuntu-latest

    steps:
    
      # deploy to azure using the v1.5.1 Microsoft function action
      - name: deploy to azure
        uses: Azure/functions-action@v1.5.1
        with:
          app-name: ${{env.AZURE_FUNCTIONAPP_NAME}}
          package: ./py-azure-functions/
          publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

  
