name: Quickpaste lint validator

on:
  push:
    branches:
      - "Development"
  
  pull_request:
    branches:
      - "Development"
  
jobs:
  auto-link-check:
    name: Validate python formatting and more
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Run lint check
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*listnener/.*.py
